version: '3.3'

services:
  batch-spark-dev: 
    build: 
      context: ../../batch
      dockerfile: Dockerfile-dev
    container_name: batch_spark_dev
    networks: ["vnet"]
    hostname: batch-spark-dev.vnet

networks:
  vnet:
    external:
      name: vnet 
