version: '3.3'

services:
  ml-dev:
    build: 
      context: ../../ml    
      dockerfile: Dockerfile-dev   
    container_name: ml-dev
    networks: ["vnet"]
    hostname: ml-dev.vnet

networks:
  vnet:
    external:
      name: vnet 
